[theme]

# Primary accent for interactive elements
primaryColor = '#2E5077'

# Background color for the main content area
backgroundColor = '#ffffff'

# Background color for sidebar and most interactive widgets
secondaryBackgroundColor = '#78B3CE'

# Color used for almost all text
textColor = '#404040'

# Font family for all text in the app, except code blocks
# Accepted values (serif | sans serif | monospace) 
# Default: "sans serif"
font = "sans serif" 